// US cities (top metros + finance hubs) plus major global financial centers.
// Format: "City, ST" for US; "City, Country" for international.
export const US_CITIES: readonly string[] = [
  "New York, NY",
  "Los Angeles, CA",
  "Chicago, IL",
  "Houston, TX",
  "Phoenix, AZ",
  "Philadelphia, PA",
  "San Antonio, TX",
  "San Diego, CA",
  "Dallas, TX",
  "San Jose, CA",
  "Austin, TX",
  "Jacksonville, FL",
  "Fort Worth, TX",
  "Columbus, OH",
  "Charlotte, NC",
  "Indianapolis, IN",
  "San Francisco, CA",
  "Seattle, WA",
  "Denver, CO",
  "Washington, DC",
  "Nashville, TN",
  "Oklahoma City, OK",
  "El Paso, TX",
  "Boston, MA",
  "Portland, OR",
  "Las Vegas, NV",
  "Detroit, MI",
  "Memphis, TN",
  "Louisville, KY",
  "Baltimore, MD",
  "Milwaukee, WI",
  "Albuquerque, NM",
  "Tucson, AZ",
  "Fresno, CA",
  "Mesa, AZ",
  "Sacramento, CA",
  "Atlanta, GA",
  "Kansas City, MO",
  "Colorado Springs, CO",
  "Miami, FL",
  "Raleigh, NC",
  "Omaha, NE",
  "Long Beach, CA",
  "Virginia Beach, VA",
  "Oakland, CA",
  "Minneapolis, MN",
  "Tulsa, OK",
  "Arlington, TX",
  "Tampa, FL",
  "New Orleans, LA",
  "Wichita, KS",
  "Cleveland, OH",
  "Bakersfield, CA",
  "Aurora, CO",
  "Anaheim, CA",
  "Honolulu, HI",
  "Santa Ana, CA",
  "Riverside, CA",
  "Corpus Christi, TX",
  "Lexington, KY",
  "Stockton, CA",
  "Henderson, NV",
  "Saint Paul, MN",
  "St. Louis, MO",
  "Cincinnati, OH",
  "Pittsburgh, PA",
  "Greensboro, NC",
  "Anchorage, AK",
  "Plano, TX",
  "Lincoln, NE",
  "Orlando, FL",
  "Irvine, CA",
  "Newark, NJ",
  "Durham, NC",
  "Chula Vista, CA",
  "Toledo, OH",
  "Fort Wayne, IN",
  "St. Petersburg, FL",
  "Laredo, TX",
  "Jersey City, NJ",
  "Chandler, AZ",
  "Madison, WI",
  "Lubbock, TX",
  "Scottsdale, AZ",
  "Reno, NV",
  "Buffalo, NY",
  "Gilbert, AZ",
  "Glendale, AZ",
  "North Las Vegas, NV",
  "Winston-Salem, NC",
  "Chesapeake, VA",
  "Norfolk, VA",
  "Fremont, CA",
  "Garland, TX",
  "Irving, TX",
  "Hialeah, FL",
  "Richmond, VA",
  "Boise, ID",
  "Spokane, WA",
  "Baton Rouge, LA",
  "Tacoma, WA",
  "San Bernardino, CA",
  "Modesto, CA",
  "Fontana, CA",
  "Des Moines, IA",
  "Moreno Valley, CA",
  "Santa Clarita, CA",
  "Fayetteville, NC",
  "Birmingham, AL",
  "Oxnard, CA",
  "Rochester, NY",
  "Port St. Lucie, FL",
  "Grand Rapids, MI",
  "Huntsville, AL",
  "Salt Lake City, UT",
  "Frisco, TX",
  "Yonkers, NY",
  "Amarillo, TX",
  "Glendale, CA",
  "Huntington Beach, CA",
  "McKinney, TX",
  "Montgomery, AL",
  "Augusta, GA",
  "Aurora, IL",
  "Akron, OH",
  "Little Rock, AR",
  "Tempe, AZ",
  "Columbus, GA",
  "Overland Park, KS",
  "Grand Prairie, TX",
  "Tallahassee, FL",
  "Cape Coral, FL",
  "Mobile, AL",
  "Knoxville, TN",
  "Shreveport, LA",
  "Worcester, MA",
  "Ontario, CA",
  "Vancouver, WA",
  "Sioux Falls, SD",
  "Chattanooga, TN",
  "Brownsville, TX",
  "Fort Lauderdale, FL",
  "Providence, RI",
  "Newport News, VA",
  "Rancho Cucamonga, CA",
  "Santa Rosa, CA",
  "Peoria, AZ",
  "Oceanside, CA",
  "Elk Grove, CA",
  "Salem, OR",
  "Pembroke Pines, FL",
  "Eugene, OR",
  "Garden Grove, CA",
  "Cary, NC",
  "Fort Collins, CO",
  "Corona, CA",
  "Springfield, MO",
  "Jackson, MS",
  "Alexandria, VA",
  "Hayward, CA",
  "Clarksville, TN",
  "Lakewood, CO",
  "Lancaster, CA",
  "Salinas, CA",
  "Palmdale, CA",
  "Hollywood, FL",
  "Springfield, MA",
  "Macon, GA",
  "Kansas City, KS",
  "Sunnyvale, CA",
  "Pomona, CA",
  "Killeen, TX",
  "Escondido, CA",
  "Pasadena, TX",
  "Naperville, IL",
  "Bellevue, WA",
  "Joliet, IL",
  "Murfreesboro, TN",
  "Midland, TX",
  "Rockford, IL",
  "Paterson, NJ",
  "Savannah, GA",
  "Bridgeport, CT",
  "Torrance, CA",
  "McAllen, TX",
  "Syracuse, NY",
  "Surprise, AZ",
  "Denton, TX",
  "Roseville, CA",
  "Thornton, CO",
  "Miramar, FL",
  "Pasadena, CA",
  "Mesquite, TX",
  "Olathe, KS",
  "Dayton, OH",
  "Carrollton, TX",
  "Waco, TX",
  "Orange, CA",
  "Fullerton, CA",
  "Charleston, SC",
  "West Valley City, UT",
  "Visalia, CA",
  "Hampton, VA",
  "Gainesville, FL",
  "Warren, MI",
  "Coral Springs, FL",
  "Cedar Rapids, IA",
  "Round Rock, TX",
  "Sterling Heights, MI",
  "Kent, WA",
  "Columbia, SC",
  "Santa Clara, CA",
  "New Haven, CT",
  "Stamford, CT",
  "Concord, CA",
  "Elizabeth, NJ",
  "Athens, GA",
  "Thousand Oaks, CA",
  "Lafayette, LA",
  "Simi Valley, CA",
  "Topeka, KS",
  "Norman, OK",
  "Fargo, ND",
  "Wilmington, NC",
  "Abilene, TX",
  "Odessa, TX",
  "Columbia, MO",
  "Pearland, TX",
  "Victorville, CA",
  "Hartford, CT",
  "Vallejo, CA",
  "Allentown, PA",
  "Berkeley, CA",
  "Richardson, TX",
  "Arvada, CO",
  "Ann Arbor, MI",
  "Rochester, MN",
  "Cambridge, MA",
  "Sugar Land, TX",
  "Lansing, MI",
  "Evansville, IN",
  "College Station, TX",
  "Fairfield, CA",
  "Clearwater, FL",
  "Beaumont, TX",
  "Independence, MO",
  "Provo, UT",
  "West Jordan, UT",
  "Murrieta, CA",
  "Palm Bay, FL",
  "El Monte, CA",
  "Carlsbad, CA",
  "North Charleston, SC",
  "Temecula, CA",
  "Clovis, CA",
  "Springfield, IL",
  "Meridian, ID",
  "Westminster, CO",
  "Costa Mesa, CA",
  "High Point, NC",
  "Manchester, NH",
  "Pueblo, CO",
  "Lakeland, FL",
  "Pompano Beach, FL",
  "West Palm Beach, FL",
  "Antioch, CA",
  "Everett, WA",
  "Downey, CA",
  "Lowell, MA",
  "Centennial, CO",
  "Elgin, IL",
  "Richmond, CA",
  "Peoria, IL",
  "Broken Arrow, OK",
  "Miami Gardens, FL",
  "Billings, MT",
  "Jurupa Valley, CA",
  "Sandy Springs, GA",
  "Gresham, OR",
  "Lewisville, TX",
  "Hillsboro, OR",
  "Ventura, CA",
  "Greeley, CO",
  "Inglewood, CA",
  "Waterbury, CT",
  "League City, TX",
  "Santa Maria, CA",
  "Tyler, TX",
  "Davie, FL",
  "Lakewood, NJ",
  "Daly City, CA",
  "Boulder, CO",
  "Allen, TX",
  "West Covina, CA",
  "Sparks, NV",
  "Wichita Falls, TX",
  "Green Bay, WI",
  "San Mateo, CA",
  "Norwalk, CA",
  "Rialto, CA",
  "Las Cruces, NM",
  "Chico, CA",
  "El Cajon, CA",
  "Burbank, CA",
  "South Bend, IN",
  "Renton, WA",
  "Vista, CA",
  "Davenport, IA",
  "Edinburg, TX",
  "Tuscaloosa, AL",
  "Carmel, IN",
  "Spokane Valley, WA",
  "San Angelo, TX",
  "Vacaville, CA",
  "Clinton, MI",
  "Bend, OR",
  "Hoover, AL",
  "Indio, CA",
  "Roanoke, VA",
  "Tracy, CA",
  "Buckeye, AZ",
  "Stamford, CT",
  "Asheville, NC",
  "Fort Smith, AR",
  "Greenville, NC",
  "Greenville, SC",
  "Bloomington, MN",
  "Bloomington, IN",
  "Iowa City, IA",
  "Reading, PA",
  "Erie, PA",
  "Brockton, MA",
  "Quincy, MA",
  "Lynn, MA",
  "Lawrence, KS",
  "St. George, UT",
  "Lehi, UT",
  "Sandy, UT",
  "Naples, FL",
  "Sarasota, FL",
  "Tempe, AZ",
  "Stillwater, OK",
  // International financial hubs (relevant to IB/PE/consulting)
  "London, UK",
  "Hong Kong",
  "Singapore",
  "Tokyo, Japan",
  "Toronto, Canada",
  "Dubai, UAE",
  "Frankfurt, Germany",
  "Zurich, Switzerland",
  "Geneva, Switzerland",
  "Sydney, Australia",
  "Mumbai, India",
  "Shanghai, China",
  "Mexico City, Mexico",
  "São Paulo, Brazil",
  "Paris, France",
  "Madrid, Spain",
  "Milan, Italy",
  "Amsterdam, Netherlands",
  "Stockholm, Sweden",
  "Dublin, Ireland",
  "Seoul, South Korea",
  "Beijing, China",
  "Vancouver, Canada",
  "Montreal, Canada",
  "Tel Aviv, Israel",
];

// Lightweight Levenshtein for typo tolerance (e.g. "Charelston" → "Charleston, SC").
function distance(a: string, b: string): number {
  if (a === b) return 0;
  if (!a.length) return b.length;
  if (!b.length) return a.length;
  const prev = new Array(b.length + 1);
  const curr = new Array(b.length + 1);
  for (let j = 0; j <= b.length; j++) prev[j] = j;
  for (let i = 1; i <= a.length; i++) {
    curr[0] = i;
    for (let j = 1; j <= b.length; j++) {
      const cost = a[i - 1] === b[j - 1] ? 0 : 1;
      curr[j] = Math.min(prev[j] + 1, curr[j - 1] + 1, prev[j - 1] + cost);
    }
    for (let j = 0; j <= b.length; j++) prev[j] = curr[j];
  }
  return prev[b.length];
}

export function searchCities(query: string, limit = 8): string[] {
  const q = query.trim().toLowerCase();
  if (q.length < 2) return [];
  const lowered = US_CITIES.map((c) => [c, c.toLowerCase()] as const);

  const starts: string[] = [];
  const includes: string[] = [];
  for (const [orig, low] of lowered) {
    const cityPart = low.split(",")[0].trim();
    if (cityPart.startsWith(q)) starts.push(orig);
    else if (low.includes(q)) includes.push(orig);
    if (starts.length >= limit) break;
  }
  const exact = [...starts, ...includes].slice(0, limit);
  if (exact.length > 0) return exact;

  // Fuzzy fallback for typos like "Charelston"
  const scored = lowered
    .map(([orig, low]) => {
      const cityPart = low.split(",")[0].trim();
      return [orig, distance(cityPart, q)] as const;
    })
    .filter(([, d]) => d <= 2)
    .sort((a, b) => a[1] - b[1]);
  return scored.slice(0, limit).map(([orig]) => orig);
}
