"use client";

import { useState } from "react";
import { BriefcaseBusiness, CheckCircle2, FileText, Network, Target } from "lucide-react";

const steps = [
  { id: "goal", label: "Goal", icon: Target },
  { id: "job", label: "Matched role", icon: BriefcaseBusiness },
  { id: "network", label: "Warm path", icon: Network },
  { id: "resume", label: "Resume", icon: FileText },
  { id: "action", label: "Next action", icon: CheckCircle2 },
] as const;

type Step = (typeof steps)[number]["id"];

export function RecruitingWorkstation() {
  const [active, setActive] = useState<Step>("goal");
  return <div className="border border-border-soft bg-white text-left "><div className="flex flex-col gap-3 border-b border-border-soft bg-surface-soft px-4 py-3 sm:flex-row sm:items-center sm:justify-between"><div><p className="font-mono text-[10px] font-bold uppercase tracking-[0.15em] text-primary">Read-only admissions showcase</p><p className="mt-1 text-sm text-text-secondary">An anonymized finance recruiting workflow. No login, personal data, or live service calls.</p></div><span className="border border-emerald-400/25 bg-emerald-400/10 px-2 py-1 font-mono text-[10px] font-bold uppercase tracking-[0.1em] text-emerald-300">Fixture data only</span></div><div className="grid min-h-[520px] lg:grid-cols-[220px_minmax(0,1fr)]"><nav aria-label="Showcase steps" className="flex overflow-x-auto border-b border-border-soft bg-surface-soft p-2 lg:flex-col lg:border-b-0 lg:border-r">{steps.map(({ id, label, icon: Icon }, index) => <button key={id} type="button" onClick={() => setActive(id)} aria-current={active === id ? "step" : undefined} className={`flex min-h-12 shrink-0 items-center gap-3 border-l-2 px-3 text-sm font-bold ${active === id ? "border-primary bg-primary-soft text-primary" : "border-transparent text-text-secondary hover:bg-surface-selected hover:text-text-primary"}`}><span className="font-mono text-[10px] text-text-faint">0{index + 1}</span><Icon className="h-4 w-4" />{label}</button>)}</nav><div className="min-w-0 p-5 sm:p-8">{active === "goal" ? <GoalPanel /> : active === "job" ? <JobPanel /> : active === "network" ? <NetworkPanel /> : active === "resume" ? <ResumePanel /> : <ActionPanel />}</div></div></div>;
}

function PanelHeading({ eyebrow, title, detail }: { eyebrow: string; title: string; detail: string }) { return <header className="border-b border-border-soft pb-5"><p className="font-mono text-[10px] font-bold uppercase tracking-[0.15em] text-primary">{eyebrow}</p><h3 className="mt-2 font-heading text-2xl font-semibold text-text-primary">{title}</h3><p className="mt-2 max-w-2xl text-base leading-6 text-text-secondary">{detail}</p></header>; }
function Metric({ label, value }: { label: string; value: string }) { return <div className="border-r border-border-soft px-3 py-4 last:border-r-0"><p className="font-mono text-[10px] font-bold uppercase tracking-[0.1em] text-text-faint">{label}</p><p className="mt-1 font-mono text-xl font-bold text-text-primary">{value}</p></div>; }

function GoalPanel() { return <><PanelHeading eyebrow="Long-term goal" title="Summer 2027 investment-banking analyst" detail="The student’s target role, firms, locations, and recruiting deadline ground every recommendation." /><dl className="mt-6 divide-y divide-border-soft border-y border-border-soft">{[["Target firms", "Bank of America, Evercore, JPMorgan"], ["Locations", "Charlotte and New York"], ["Recruiting deadline", "September 15, 2026"], ["Weekly relationship goal", "3 substantive conversations"]].map(([label, value]) => <div key={label} className="grid gap-1 py-4 sm:grid-cols-[180px_1fr]"><dt className="text-sm font-bold text-text-secondary">{label}</dt><dd className="text-base text-text-primary">{value}</dd></div>)}</dl><div className="mt-6 border border-primary/25 bg-primary-soft p-4"><p className="font-mono text-[10px] font-bold uppercase tracking-[0.12em] text-primary">Do now</p><p className="mt-2 text-lg font-semibold text-text-primary">Review the BofA LevFin analyst role</p><p className="mt-1 text-sm text-text-secondary">Best combination of profile fit, Charlotte preference, listing freshness, and network strength.</p></div></>; }
function JobPanel() { return <><PanelHeading eyebrow="Official listing match" title="Leveraged Finance Summer Analyst" detail="KithNode scores public official listings against profile evidence and the student’s real network." /><div className="mt-6 grid grid-cols-4 border-y border-border-soft"><Metric label="Overall fit" value="89" /><Metric label="Profile" value="91" /><Metric label="Network" value="86" /><Metric label="Freshness" value="2d" /></div><div className="mt-6"><p className="font-mono text-[10px] font-bold uppercase tracking-[0.12em] text-text-faint">Why it matches</p><ul className="mt-3 space-y-3 text-base text-text-primary"><li>• Coursework and internship evidence support financial modeling and transaction analysis.</li><li>• Charlotte matches the stated location preference.</li><li>• Three alumni relationships create a credible warm path into the employer.</li></ul></div></>; }
function NetworkPanel() { return <><PanelHeading eyebrow="Relationship intelligence" title="A two-hop path into the team" detail="The recommendation shows why each person matters without fabricating closeness or sending a message." /><div className="mt-8 flex flex-col items-stretch gap-2 sm:flex-row sm:items-center"><Person initials="JD" name="Student" detail="UNC '27" /><Arrow /><Person initials="AM" name="Alex Morgan" detail="Warm · UNC alumnus" /><Arrow /><Person initials="JS" name="Jordan Smith" detail="BofA LevFin VP" /></div><div className="mt-8 border-y border-border-soft py-4"><p className="text-base font-semibold text-text-primary">Recommended relationship action</p><p className="mt-1 text-sm text-text-secondary">Ask Alex for perspective on the group before requesting an introduction. The user reviews any draft before sending.</p></div></>; }
function Person({ initials, name, detail }: { initials: string; name: string; detail: string }) { return <div className="min-w-0 flex-1 border border-border-soft bg-white p-4"><div className="flex h-9 w-9 items-center justify-center bg-primary-soft font-mono text-sm font-bold text-primary">{initials}</div><p className="mt-3 text-base font-semibold text-text-primary">{name}</p><p className="mt-1 text-sm text-text-secondary">{detail}</p></div>; }
function Arrow() { return <span className="self-center font-mono text-text-faint">→</span>; }
function ResumePanel() { return <><PanelHeading eyebrow="Evidence-backed tailoring" title="Resume variant for BofA LevFin" detail="The variant changes emphasis and wording only where the student’s evidence bank supports it." /><div className="mt-6 border border-border-soft bg-white p-6 text-slate-900"><div className="border-b border-slate-300 pb-3 text-center"><p className="font-serif text-lg font-bold">Jordan Davis</p><p className="text-[11px]">Chapel Hill, NC · jordan@example.com</p></div><p className="mt-4 font-serif text-[11px] font-bold uppercase tracking-widest">Experience</p><p className="mt-2 font-serif text-[11px] font-bold">Finance Intern · Regional Advisory Partners</p><p className="mt-1 font-serif text-[10px] leading-4">• Built a three-statement operating model and comparable-company analysis supporting a live sell-side mandate.</p><p className="mt-1 font-serif text-[10px] leading-4">• Synthesized market and customer diligence into an executive-ready investment committee brief.</p></div><p className="mt-3 text-sm text-text-secondary">Every tailored bullet points back to recorded experience. Unsupported claims are rejected.</p></>; }
function ActionPanel() { return <><PanelHeading eyebrow="Application workspace" title="One clear next action" detail="The opportunity, relationship path, resume, deadline, and timeline stay together after discovery." /><div className="mt-6 overflow-x-auto border border-border-soft"><table className="w-full min-w-[720px] text-left"><thead className="bg-surface-soft"><tr>{["Company / role", "Status", "Deadline", "Fit / network", "Resume", "Next action"].map((label) => <th key={label} className="border-b border-border-soft px-3 py-3 font-mono text-[10px] uppercase tracking-[0.1em] text-text-faint">{label}</th>)}</tr></thead><tbody><tr><td className="px-3 py-4"><p className="font-semibold text-text-primary">Bank of America</p><p className="text-sm text-text-secondary">Leveraged Finance Summer Analyst</p></td><td className="px-3 py-4"><span className="border border-sky-400/30 bg-sky-400/10 px-2 py-1 text-xs font-bold text-sky-300">PREPARING</span></td><td className="px-3 py-4 font-mono text-sm text-text-primary">Sep 15</td><td className="px-3 py-4 font-mono text-sm"><span className="text-sky-300">89</span><span className="text-text-faint"> / </span><span className="text-emerald-300">86</span></td><td className="px-3 py-4 text-sm text-text-primary">BofA variant</td><td className="px-3 py-4 text-sm text-text-primary">Ask Alex for group perspective</td></tr></tbody></table></div><div className="mt-6 border border-emerald-400/25 bg-emerald-400/[0.07] p-4"><p className="text-sm font-bold text-emerald-300">User approval remains the boundary</p><p className="mt-1 text-sm text-text-secondary">The showcase cannot send, apply, enrich, publish, or change real data.</p></div></>; }
